### ISSUE TITLE
Just a question...

### ISSUE THREAD

**Issue by mamarilmanson** [Spekular/Vino#20]
I just want to ask? I can't imagine how this is going to work? please enlighten me? :)

**Comment by Spekular** [comment]
It's just a side project of mine at the moment, I'd like to have it private
(I'm sure the code quality is terrible) but you have to pay for that.

From the artist's perspective, the goal is to eventually have an easy
editor. The artist titles the current page, browses to an image file for
the background, writes the prompt, and adds a number of responses along
with the pages they lead to.

On the backend side this will write a text file and copy the image to a
directory for the "story". This will also be the initial way to create
stories. These files are then read at runtime based on what path the player
chooses.

To "install" a story, the player downloads a folder containing some
metadata and the pages. They place this in some location (eventually you
should be able to specify multiple locations for stories to be placed)
where ViNo reads it.

I've got the structure pretty well worked out in my head, but implememting
it is a bit tougher, obviously. I'm not allowed to accept any help with the
code since this is also a project for school, but if you have any critique
regarding the structure I think it should be fine, maybe.

**Comment by mamarilmanson** [comment]
if I have time I will try to understand it... :)
